################################# Default configuration ###################
# provide your domain here
baseURL = "https://dpsoft-official.github.io/next.ava-doc"
# theme
theme = "dot"
# site title
title = "راهنمای سامانه آوا"
# disable language
disableLanguages = []
# google analytics
googleAnalytics = "" # paste your analytics ID here. (Ex: UA-123-45)

# unsafe html
[markup.goldmark.renderer]
unsafe= true

################################# navigation ################################
[[menu.main]]


[[menu.main]]
name = "راهنما"
url = "administrator"
weight = 1

[[menu.main]]
name = "سوالات متداول"
url = "faq"
weight = 2

[[menu.main]]
name = "ارتباط با ما"
url = "contact"
weight = 3


############################# Default Parameters ##########################
[params]
# logo is for all page
logo = ""
# logo white is for homepage logo, you can use colorful logo too...
logo_white = ""
# when logo is empty, it will shown your site title

# customize color
primary_color = "#3677d2"
body_color = "#f9f9f9"
text_color = "#636363"
text_color_dark = "#242738"
white_color = "#ffffff"
light_color = "#f8f9fa"

# font family
font_family = "Vazir"

# contact form action
contact_form_action = "#" # contact form works with : https://formspree.io


############################## social links ##############################
[[params.social]]
icon = "ti-instagram" # themify icon pack : https://themify.me/themify-icons
link = "https://www.instagram.com/dpsoft.ir/"

[[params.social]]
icon = "ti-video-clapper" # themify icon pack : https://themify.me/themify-icons
link = "https://www.aparat.com/dpsoft"
  
[[params.social]]
icon = "ti-github" # themify icon pack : https://themify.me/themify-icons
link = "https://github.com/dpsoft-official"
  
[[params.social]]
icon = "" # themify icon pack : https://themify.me/themify-icons
link = "#"

################################ English Language ######################
[Languages.en]
languageName = "En"
languageCode = "en-us"
weight = 1
home = "خانه"
copyright = "سامانه‌ی ارتباط با مشتری [آوا](https://avaa-crm.ir)"

# banner
[Languages.en.params.banner]
title = "راهنمای سامانه آوا"
subtitle = ""
bg_image = "images/banner.jpg"
placeholder = "سوالی دارید؟ "

# call to action
[Languages.en.params.cta]
enable = true
title = "جواب سوال خود را پیدا نکردید؟"
#content = "سوالات خود را با در میان بگذارید. همکاران ما در کوتاه ترین زمان ممکن پاسخ شما را خواهند داد"
# call to action button
[Languages.en.params.cta.button]
enable = true
label = "ارتباط با ما"
link = "contact"

languagedirection = "rtl"
